#!/usr/bin/expect --
spawn ssh -o "ServerAliveInterval 10" -X twong@172.16.0.218
expect "password:"
send "zoove123\r"
expect "twong"
send ". /home/twong/rel4_7_2_trunk/build/rhel4-configure\r"
send ". /home/twong/rel4_7_2_trunk/ful/bridge/env\r"
send "cd /home/twong/rel4_7_2_trunk\r"
interact
