#!/usr/bin/expect --

set timeout 60
spawn ssh -o "ServerAliveInterval 30" -X twong@172.16.4.83
expect "password:"
send "zoove123\r"
expect "twong"
send "cd /home/twong/rel4_7_trunk/sigtran/caa\r"
send "wireshark &\r"
interact
